### ISSUE TITLE
'module' object has no attribute 'read_dot'

### ISSUE THREAD

**Issue by agasthik** [jantman/misc-scripts#1]
Encountered this error when executing the dot_find_cycles.py script

```
[root@myhost vagrant]# ./dot_find_cycles.py /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot
Traceback (most recent call last):
  File "./dot_find_cycles.py", line 65, in <module>
    main()
  File "./dot_find_cycles.py", line 57, in main
    G = nx.DiGraph(nx.read_dot(path))
AttributeError: 'module' object has no attribute 'read_dot'
[root@myhost vagrant]#
```

**Comment by jantman** [comment]
@agasthik this script was written over 4 years ago. I believe that networkx version 1.10 or less should work.
